#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ,               sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed, encoderPort, dgtl1)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, encoderPort, dgtl3)
#pragma config(Motor,  port5,           barrelMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           barrelServo,   tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//int test;

task main()
{

	while(1){

		while(motor[barrelServo]<100)
		{
			motor[barrelServo]= motor[barrelServo]+1;
			wait1Msec(10);

		}
		wait1Msec(1000);

		while(motor[barrelServo]>-100)
		{
			motor[barrelServo]= motor[barrelServo]-1;
			wait1Msec(10);
		}
		wait1Msec(5000);
	}

}
