#pragma config(Sensor, in1,    sharp,          sensorAnalog)
#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  limit,          sensorTouch)
#pragma config(Sensor, dgtl8,  light,          sensorDigitalIn)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed, encoderPort, dgtl1)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, encoderPort, dgtl3)
#pragma config(Motor,  port5,           barrelMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           barrelServo,   tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//int leftEncode;
//int rightEncode;

void move_to_encoder(int port, int step, int speed){
	resetMotorEncoder(port);
	if(step>0)
	{
		while(getMotorEncoder(port) < step)
		{
		motor[port] = speed;
		}
	}
	else
	{
		while(getMotorEncoder(port) > step)
		{
		motor[port] = -speed;
		}
	}
}

task main()
{

	while(1){
		move_to_encoder(rightMotor,100,100);
		move_to_encoder(leftMotor,100,100);
		wait1Msec(100);
		move_to_encoder(rightMotor,-100,100);
		move_to_encoder(leftMotor,-100,100);
	}

}
